### ISSUE TITLE
PWS rejects wind direction

### ISSUE THREAD

**Issue by tailwheel** [FlyingDiver/Indigo-WeatherLinkLive#1]
AerisWeather expects wind direction to be an integer. The plugin submits it as a float, so it is rejected.

**Comment by FlyingDiver** [comment]
Which uploader is Aeris?  I don't have that one listed.

**Comment by tailwheel** [comment]
It’s PWS:
PWSWeather - Bring Your Weather to Life <https://www.pwsweather.com/>

Owned and supported by AerisWeather.

**Comment by FlyingDiver** [comment]
My wind directions are integers.
<img width="402" alt="Screen Shot 2020-12-06 at 1 04 00 PM" src="https://user-images.githubusercontent.com/72976/101288245-884f9780-37c3-11eb-9123-0bf48d4abc9a.png">

**Comment by tailwheel** [comment]
From Event Log:

WeatherLink Live Debug          *PWS: PWS upload data = {'dateutc': '2020-12-06 18:08:25', 'softwaretype': 'Indigo WeatherLink Live', 'tempf': 51.1, 'yearrainin': 0.39, 'windspeedmph': 2.0, 'baromin': 25.07, 'rainin': 0.0, 'windgustmph': 8.0, 'humidity': 27.0, 'winddir': 198.0, 'dewptf': 18.1, 'monthrainin': 0.0, 'dailyrainin': 0.0, 'action': 'updateraw’,...'}

**Comment by FlyingDiver** [comment]
I'm uploading to PWS and not getting any errors.

**Comment by FlyingDiver** [comment]
Or does it not return an error on the upload?  Is it just logged on the site?

**Comment by FlyingDiver** [comment]
Where are you seeing the error?  Screen shot?

**Comment by tailwheel** [comment]
I should have double checked - It looks like PWS fixed wind direction at their end, a few weeks ago.

Their pressure is still reporting absolute as opposed to MSL. A different issue…

Thanks.

**Comment by FlyingDiver** [comment]
Which is fixed in the latest plugin.  You can select which pressure you want to upload.

**Comment by tailwheel** [comment]
Just installed latest. Perfect!

Thanks Joe!
Greg
