### ISSUE TITLE
WeatherLink units

### ISSUE THREAD

**Issue by EagleyeI** [FlyingDiver/Indigo-WeatherLinkLive#2]
Have purchased the suite of Davies weather stations and successfully connected to indigo via your Plugin.  However all data is showing up in imperial not metric.  I have changed the units on the WeatherLink site, but it’s not changing in indigo  Are you able to offer any suggestion on how this can be corrected.

**Comment by autolog** [comment]
I have been invited to do a pull request for this. I will do the changes and then do that. :)

**Comment by FlyingDiver** [comment]
Release 0.2.0.
