### ISSUE TITLE
send_update error: [Errno 60] Operation timed out

### ISSUE THREAD

**Issue by akataz04** [FlyingDiver/Indigo-WeatherLinkLive#5]
Since the python 3 upgrade, getting the error:  

WeatherLink Live Error          WeatherLink Live-CWOP upload: send_update error: [Errno 60] Operation timed out

Versions:

- Indigo: 2022.1.2
- Plugin: v2022.0.0

**Comment by FlyingDiver** [comment]
I no longer have access to the CWOP site, so I can't fix this.  I'll have to remove that function, I guess.
